apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: k3d                # skaffold 실행시 -p로 정의된 profile
    build:
      local:
        push: true # false는 로컬 테스트
      artifacts:
        - image: docker.io/hotoron/demo-fe # on dev server (docker hub에 push하고 실행)
          # - image: demo-api   # local(로컬/push없이 실행만)
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=k3d"  # jib 플러그인을 통해 dev profile에 대해 수행
            fromImage: docker.io/library/eclipse-temurin:17-jre-alpine         # 실행을 위한 runtime image
    deploy:
      kubectl:
        manifests:
          # Apply Ingress Controller to cluster
          - https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
          - k8s/k3d/*.yml

