apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: kind2                 # skaffold 실행시 -p로 정의된 profile
    build:
      local:
        push: true # false는 로컬 테스트
      artifacts:
        - image: docker.io/hotoron/demo-fe # on dev server (docker hub에 push하고 실행)
          # - image: demo-api   # local(로컬/push없이 실행만)
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"  # jib 플러그인을 통해 dev profile에 대해 수행
            fromImage: docker.io/library/eclipse-temurin:17-jre-alpine         # 실행을 위한 runtime image
    deploy:
      kubectl:
        manifests:
          - k8s/board-fe-deploy.yml
          - k8s/board-fe-headless-svc.yml
          - k8s/board-fe-ingress.yml
#          - k8s/board-fe-ns.yml

