#server:
#  port: 9321
#
#api:
#  simple:
#    url: http://localhost:9320/api # 다음주소가 feignClient가 접속할 연계 대상 서버
#
#feign:
#  circuitbreaker:  # feign에서도 circuit breaker를 적용할 수 있다.
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: FULL ##basic