server:
  port: 8081

#Feign로그는 debug보다 높은 레벨에서는 나오지 않는다.
logging:
  level:
    root: info
    com.example: info # 공통내용만 작성하기

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#  mvc:
#    static-path-pattern: /static/**
  profiles:
    active: default

---